### ISSUE TITLE
Proxy

### ISSUE THREAD

**Issue by Terxeno** [indigo-sadland/quick-tricks#3]
Can you add Option Proxy? or trough Torify proxy?

**Comment by indigo-sadland** [comment]
Good idea! I think yes, I could add such functionality. Thank you for your request.

**Comment by indigo-sadland** [comment]
https://github.com/indigo-sadland/quick-tricks/commit/455010e1faa0c647a0a84ec3ea1bb958c2554d83

http/socks5 option added, but I haven't tested it properly though.

**Comment by Terxeno** [comment]
Yes, it works but with the XSS option it doesn't seem to. Also no **quick optio**n, although it's listed in the documentation.

**Comment by indigo-sadland** [comment]
Somehow I missed the part of "quick"  code... 

As for XSS, the module only combines payloads with a target url (_without connection to a target_) and returns urls for you to check.

**Comment by Terxeno** [comment]
Thanx for fix "quick", now it's work fine.
`As for XSS, the module only combines payloads` ok i see, thanx for answer
